"""
CampusCoPilot – Pydantic schemas for request / response validation.
"""

from __future__ import annotations
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


# ── Syllabus parsing ─────────────────────────────────────────────────
class ExtractedTopic(BaseModel):
    """A single topic extracted from a syllabus PDF."""
    topic: str
    subtopics: List[str] = Field(default_factory=list)
    estimated_hours: Optional[float] = None
    covered: bool = False


class SyllabusParseResponse(BaseModel):
    """Result of parsing + topic extraction from a syllabus."""
    filename: str
    total_pages: int
    topics: List[ExtractedTopic]
    raw_text_preview: str = Field(
        "", description="First 500 chars of extracted text"
    )


# ── Study plan / campaign ────────────────────────────────────────────
class DailyTask(BaseModel):
    """A single task within a study day."""
    time_slot: str = Field(..., examples=["09:00-10:30"])
    task: str
    resource_hint: Optional[str] = None
    priority: str = Field("medium", examples=["high", "medium", "low"])


class DayPlan(BaseModel):
    """All tasks for one calendar day."""
    day: str = Field(..., examples=["Monday – Week 1"])
    date: Optional[str] = None
    tasks: List[DailyTask]
    focus_topic: str


class WeekPlan(BaseModel):
    """One week inside a study campaign."""
    week_number: int
    theme: str
    days: List[DayPlan]


class StudyCampaign(BaseModel):
    """A full weekly study campaign generated by the Planner Agent."""
    student_name: Optional[str] = None
    total_weeks: int
    hours_per_day: float
    weekly_plans: List[WeekPlan]


# ── Student persona / constraints ────────────────────────────────────
class StudentConstraints(BaseModel):
    """Optional constraints the student can provide."""
    name: Optional[str] = "Student"
    available_hours_per_day: float = Field(4.0, ge=0.5, le=16.0)
    weak_subjects: List[str] = Field(default_factory=list)
    language_preference: str = "English"
    fragmented_schedule: bool = False
    exam_date: Optional[str] = None  # ISO date string
    additional_notes: Optional[str] = None
    additional_events: Optional[List[Dict[str, Any]]] = Field(default_factory=list)


# ── Disruption simulation (MVP mock) ────────────────────────────────
class DisruptionEvent(BaseModel):
    """A simulated disruption, e.g. class canceled."""
    event_type: str = Field(..., examples=["class_canceled", "extra_assignment", "sick_day"])
    affected_day: str
    description: Optional[str] = None


class ReplanRequest(BaseModel):
    """Ask the Planner to adjust the campaign for a disruption."""
    campaign: StudyCampaign
    disruption: DisruptionEvent
    constraints: Optional[StudentConstraints] = None


# ═══════════════════════════════════════════════════════════════════════
#  EVENT SCHEDULER – Input / Output schemas
# ═══════════════════════════════════════════════════════════════════════

class EventInput(BaseModel):
    """
    A single event the student wants scheduled.
    - Fixed events have a specific date + start_time (e.g. a class).
    - Dynamic events only have a deadline; the AI decides when to slot them.
    """
    event_name: str = Field(..., examples=["Math Homework", "Physics Lab"])
    difficulty: str = Field("medium", examples=["easy", "medium", "hard"])
    time_required_hours: float = Field(..., ge=0.25, examples=[1.5, 3.0])
    deadline: str = Field(
        ...,
        description="ISO date string (YYYY-MM-DD). The event MUST be completed by this date.",
        examples=["2026-03-15"],
    )
    event_type: str = Field(
        ...,
        description="'fixed' = locked date/time, 'dynamic' = AI picks the slot",
        examples=["fixed", "dynamic"],
    )
    # Only used when event_type == "fixed"
    fixed_date: Optional[str] = Field(
        None,
        description="ISO date (YYYY-MM-DD) when this event occurs. Required if event_type='fixed'.",
        examples=["2026-03-10"],
    )
    fixed_start_time: Optional[str] = Field(
        None,
        description="24h start time for fixed events, e.g. '14:00'. Required if event_type='fixed'.",
        examples=["14:00"],
    )
    notes: Optional[str] = None


class SchedulerInput(BaseModel):
    """Payload sent to the scheduler endpoint."""
    events: List[EventInput] = Field(..., min_length=1)
    available_hours_per_day: float = Field(8.0, ge=1, le=18)
    day_start_time: str = Field("08:00", examples=["08:00", "09:00"])
    day_end_time: str = Field("22:00", examples=["20:00", "22:00"])
    preferred_break_minutes: int = Field(15, ge=0, le=60)


# ── Scheduler output ─────────────────────────────────────────────────

class ScheduledSlot(BaseModel):
    """One time-block in the output calendar."""
    event_name: str
    date: str = Field(..., description="YYYY-MM-DD")
    start_time: str = Field(..., examples=["09:00"])
    end_time: str = Field(..., examples=["10:30"])
    difficulty: str
    is_fixed: bool = Field(False, description="True if this was a fixed event")
    notes: Optional[str] = None


class ScheduleDay(BaseModel):
    """All slots for a single calendar day."""
    date: str
    day_name: str = Field(..., examples=["Monday"])
    slots: List[ScheduledSlot]
    free_hours: float = Field(0, description="Unscheduled hours remaining")


class SchedulerOutput(BaseModel):
    """Complete optimised schedule returned by the AI."""
    schedule: List[ScheduleDay]
    total_events: int
    fixed_events: int
    dynamic_events: int
    warnings: List[str] = Field(
        default_factory=list,
        description="E.g. 'Event X cannot fit before its deadline'",
    )


# ══════════════════════════════════════════════════════════════════════
#  SEMESTER PLANNER – Multi-subject support
# ══════════════════════════════════════════════════════════════════════

class SemesterInfo(BaseModel):
    """Core semester metadata."""
    university: str = ""
    branch: str = ""  # e.g. "Computer Science", "Mechanical Engineering"
    semester_type: str = Field("autumn", description="'spring' or 'autumn'")
    semester_number: Optional[str] = None  # e.g. "5th"
    semester_start: Optional[str] = None  # ISO date
    midterm_start: Optional[str] = None
    midterm_end: Optional[str] = None
    endterm_start: Optional[str] = None
    endterm_end: Optional[str] = None
    dates_released: bool = False


class SubjectEntry(BaseModel):
    """A single subject in the semester."""
    name: str
    credits: Optional[int] = None
    topics: List[ExtractedTopic] = Field(default_factory=list)
    pdf_uploaded: bool = False
    weak: bool = False  # student marks this subject as weak
    target_completion_date: Optional[str] = None


class SemesterPlanConstraints(BaseModel):
    """Extended constraints for multi-subject semester planning."""
    name: Optional[str] = "Student"
    available_hours_per_day: float = Field(4.0, ge=0.5, le=16.0)
    language_preference: str = "English"
    fragmented_schedule: bool = False
    study_style: str = "balanced"  # intensive, balanced, pomodoro, spaced
    target_career_track: str = Field("Core Engineering", examples=["Core Engineering", "IT & Software", "Management", "Research"])
    additional_notes: Optional[str] = None
    unavailable_hours: Optional[str] = None
    additional_events: Optional[List[Dict[str, Any]]] = Field(default_factory=list)
